apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
        - name: backend-container
          image: docker.io/simple_server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_LISTEN_ADDR
              value: ":8080"
            - name: ADMIN_LOGIN
              value: "adminlogin"
            - name: ADMIN_PASSWORD
              value: "adminpassword"
  selector:
    matchLabels:
      app: simple-server
